export const durations = [
  '3 Months',
  '6 Months',
  '9 Months',
  '1 Year',
  '2 Years',
  '3 Years',
  '4 Years',
  '5 Years',
  '6 Years',
  '7 Years',
  '8 Years',
  '9 Years',
  '10 Years',
  '11 Years',
  '12 Years',
  '13 Years',
  '14 Years',
  '15 Years',
  'More Than 15 Years',
];
export const ownershipType = ['Owned - Original Owner', 'Owned', 'Leased', 'Lien'];
export const PriorLiabilityLimits = [
  {
    text: "I don't know",
    value: 'IDK',
  },
  {
    text: '10/20',
    value: '10/20',
  },
  {
    text: '15/30',
    value: '15/30',
  },
  {
    text: '20/40',
    value: '20/40',
  },
  {
    text: '25/25',
    value: '25/25',
  },
  {
    text: '25/50',
    value: '25/50',
  },
  {
    text: '50/50',
    value: '50/50',
  },
  {
    text: '50/100',
    value: '50/100',
  },
  {
    text: '100/100',
    value: '100/100',
  },
  {
    text: '100/300',
    value: '100/300',
  },
  {
    text: '250/500',
    value: '250/500',
  },
  {
    text: '300/300',
    value: '300/300',
  },
  {
    text: '500/500',
    value: '500/500',
  },
  {
    text: '500/500',
    value: '500/500',
  },
  {
    text: '1000/1000',
    value: '1000/1000',
  },
  {
    text: '55CSL',
    value: '55CSL',
  },
  {
    text: '100CSL',
    value: '100CSL',
  },
  {
    text: '300CSL',
    value: '300CSL',
  },
  {
    text: '500CSL',
    value: '500CSL',
  },
  {
    text: 'None',
    value: 'None',
  },
];

export const WhyNoInsurance = [
  'Active Military Duty',
  'Driving A Company Car',
  'Driving A Car Owned By A Relative',
  'Has Not Owned Or Operated A Vehicle',
  'Owned Veh Parked/Stored Off Road/Not Driven',
  'Non-Payment',
  'Other',
];

export const currentLivingSituation = [
  'Home (owned)',
  'Condo (owned)',
  'Apartment',
  'Rental Home/Condo',
  'Mobile Home',
  'Live With Parents',
  'Other',
];

export const incidentType = [
  { text: 'Accident', value: 'accident' },
  { text: 'Violation', value: 'violation' },
  { text: 'Loss', value: 'loss' },
];

export const incidentDescriptions = {
  accident: [
    'At Fault With Injury',
    'At Fault With No Injury',
    'Not At Fault With Injury',
    'Not At Fault With No Injury',
  ],
  violation: [
    'Careless Driving',
    'Cell Phone',
    'Child Safety Restraint',
    'Defective Equipment',
    'Divided Highways',
    'Double Lines',
    'Driving Left Of Center',
    'Driving On Suspended License',
    'Driving Too Slow',
    'Driving Without Lights',
    'DUI',
    'Eluding Police',
    'Failure To Obey Signal',
    'Failure To Observe A Safety Zone',
    'Failure To Show Documents',
    'Failure To Stop',
    'Failure To Yield',
    'False Reporting',
    'Felony',
    'Following Too Closely',
    'Hit And Run',
    'Homicide',
    'Illegal Turn',
    'Improper Loads',
    'Improper Parking',
    'Improper Passing',
    'Leaving Scene Of An Accident',
    'Motorcycle Violation',
    'Open Container',
    'Operating Vehicle Without Permission',
    'Out Of State',
    'Passing School Bus',
    'Racing/Drag Racing',
    'Recreational Vehicle',
    'Refusal To Submit To Chemical Test',
    'Seat Belt',
    'Speeding 1-5',
    'Speeding 6-10',
    'Speeding 11-15',
    'Speeding 16-20',
    'Speeding 21+',
    'Speed Over 100mph',
    'Suspension',
    'Texting while Driving',
    'Towing',
    'Transportation Of Hazardous Materials',
    'Unsafe Operation Of A Motor Vehicle',
    'Vehicle Theft',
    'Wrong Way/Wrong Lane',
    'Other Major',
    'Other Minor',
    'Ticket Violation Not Listed',
  ],
  loss: [
    'Fire',
    'Flood',
    'Glass/Windshield',
    'Hail',
    'Hit Animal',
    'Hurricane',
    'Theft',
    'Tornado',
    'Towing',
    'Vandalism',
    'Wind',
    'All Other',
  ],
};

export const currentCarriers = [
  '1st Auto',
  '21st Century',
  'A.Central',
  'AAA Insurance',
  'AARP',
  'Acadia',
  'Acceptance Insurance',
  'Access General',
  'Ace',
  'Acuity',
  'Adirondack Ins Exchange',
  'Aegis',
  'Affirmative',
  'AgWorkers Mutual Auto',
  'AIC',
  'AIG',
  'Alert Auto Insurance Company',
  'Alfa Alliance',
  'Alfa Insurance Companies',
  'Alinsco',
  'Allied',
  'Allied Trust Insurance Company',
  'Allstate',
  'America First',
  'American Commerce',
  'American Family',
  'American Freedom Insurance Company',
  'American Modern',
  'American National',
  'Amerisure',
  'AmFam Connect',
  'Amica',
  'AmShield',
  'AmWINS Star',
  'Anchor General',
  'Arbella',
  'Arrowhead',
  'Arrowhead Everest',
  'ASI Select Auto Insurance Corp',
  'Aspen',
  'Aspire',
  'AssuranceAmerica',
  'Atlantic Mutual',
  'Austin Mutual',
  'Auto-Owners',
  'Autoone',
  'AutoTex',
  'Badger Mutual',
  'Balboa',
  'Bankers',
  'Beacon National',
  'Bear River Mutual',
  'Brethern Mutual',
  'Bristol West',
  'Buckeye',
  'California Casualty',
  'Cameron Mutual',
  'Capital Insurance Group',
  'Capitol Insurance Company',
  'Casualty Underwriters Insurance Company',
  'Celina',
  'Centennial',
  'Central Mutual of OH',
  'Century National',
  'Charter',
  'Chubb',
  'Cincinnati',
  'Cincinnati Casualty',
  'Cincinnati Insurance',
  'Citizens',
  'Clearcover',
  'CNA',
  'Colonial Penn',
  'Colorado Casualty',
  'Columbia',
  'Commerce',
  'Commerce West',
  'Commonwealth',
  'Concord Group Insurance',
  'Connect Banner',
  'Constitutional Casualty',
  'Consumers',
  'Cornerstone',
  'Country Insurance',
  'Countryway Insurance',
  'Countrywide',
  'Cover Insurance',
  'CSE',
  'Cumberland',
  'Dairyland',
  'Deerbrook',
  'Delta Lloyds Insurance Company',
  'Depositors',
  'Direct',
  'Direct General',
  'Discovery',
  'Donegal',
  'Drive',
  'Electric',
  'Elephant Insurance',
  'Embark General',
  'EMC',
  'Empower',
  'Encompass',
  'Encova Exceed',
  'Enumclaw Insurance',
  'Erie',
  'Esurance',
  'Eveready',
  'Explorer',
  'Farm Bureau',
  'Farmers Agent360',
  'Farmers Insurance',
  'Federated',
  'Fidelity',
  'Financial Indemnity',
  'Firemans Fund',
  'First Acceptance',
  'First American',
  'First Auto',
  'First Chicago',
  'First Connect',
  'Fitchburg Mutual',
  'Flagship Insurance',
  'Foremost',
  'Founders',
  'Frankenmuth',
  'Fred Loya',
  'Fremont Insurance',
  'GAINSCO Auto Insurance',
  'Gateway',
  'Geico',
  'General Casualty',
  'Germania Insurance',
  'Germantown Mutual',
  'Goodville Mutual',
  'Grange',
  'Grange Insurance Association',
  'GRE/Go America',
  'Great American',
  'Grinnell',
  'Guide One',
  'Hallmark Insurance Company',
  'Hanover',
  'Harbor',
  'Harleysville',
  'Hartford OMNI',
  'Hastings Mutual',
  'Haulers Insurance Company',
  'Hawkeye Security',
  'HDI',
  'Hochheim Prairie Insurance',
  'Homesite',
  'Horace Mann',
  'Houston General',
  'IFA',
  'Imperial Casualty',
  'IMT Ins',
  'Indiana',
  'Indiana Farmers',
  'Infinity',
  'Infinity RSVP',
  'Infinity Special',
  'InsureMax',
  'Insurequest',
  'Integon',
  'Integrity',
  'Iowa Mutual Insurance Company',
  'Kemper',
  'Kemper Specialty',
  'Kingsway',
  'Legacy - Arizona Auto Ins. Co',
  'LeMars Insurance',
  'Liberty Mutual',
  'Liberty Northwest',
  'Madison Mutual Insurance Company',
  'Maidstone Insurance',
  'MAIF',
  'Main Street America',
  'MAPFRE',
  'MAPFRE Protection',
  'MAPFRE Road America',
  'Markel',
  'Maryland Auto Insurance',
  'Mendakota',
  'Mendota',
  'Merchants Group',
  'Mercury',
  'MetLife',
  'Michigan Insurance Company',
  'Michigan Millers Mutual Insurance Company',
  'Mid-Continent',
  'Midwestern Indemnity',
  'Mile Auto',
  'MMG Insurance Company',
  'Montgomery',
  'Motion Auto',
  'Motor Club Insurance Company',
  'Motorists Mutual',
  'MSA',
  'Mt. Washington',
  'Mutual Benefit',
  'Mutual of Enumclaw',
  'National General',
  'National Lloyds Insurance Company',
  'Nationwide',
  'New York Central Mutual',
  'NJ Manufacturers',
  'NJ Skylands',
  'NLC Insurance Companies',
  'Nodak Mutual',
  'Northern Neck Insurance Company',
  'Northstar',
  'NYAIP',
  'NYCM Standard',
  'Occidental',
  'Ocean Harbor',
  'Ohio Casualty',
  'Ohio Mutual',
  'Omaha P/C',
  'Omni Insurance Co',
  'One Beacon',
  'Oregon Mutual',
  'Palisades',
  'Partners Mutual Insurance',
  'Patriot',
  'Patrons Oxford',
  'Peerless/Montgomery',
  'Pekin',
  'Pemco',
  'Peninsula Insurance Companies',
  'Penn National',
  'Personal Service Insurance',
  'Phoenix Indemnity',
  'Pioneer State Mutual',
  'Plymouth Rock',
  'Plymouth Rock Teachers Plan of NJ',
  'Preferred Mutual',
  'Proformance',
  'Progressive',
  'Providence Mutual Fire Insurance Company',
  'Prudential',
  'QBE',
  'Quincy Mutual',
  'RAM Mutual Insurance Company',
  'Republic',
  'Response',
  'Rockford Mutual',
  'Rockingham Casualty Company',
  'Royal and Sun Alliance',
  'Safe Auto',
  'Safeco',
  'Safety Insurance Company',
  'Safeway',
  'Sagamore',
  'SECURA',
  'Selective',
  'Sentry Ins',
  'Sheboygan Falls Insurance',
  'Shelter Insurance',
  'Southern County',
  'Southern Mutual',
  'Southern Trust',
  'St. Paul/Travelers',
  'Standard Mutual',
  'Star Casualty',
  'State Auto',
  'State Farm',
  'Stillwater',
  'Stonegate',
  'Sublimity Insurance Company',
  'Sun Coast Platinum',
  'Texas Ranger MGA',
  'The General',
  'The Hartford',
  'Topa',
  'Tower',
  'Travelers',
  'Trexis',
  'TWFG',
  'Unigard',
  'United Automobile',
  'United Fire and Casualty',
  'United Heritage Property and Casualty Company',
  'United Home',
  'Unitrin',
  'Universal',
  'USAA',
  'Utica National',
  'Victoria',
  'Wadena Insurance Company',
  'Wayne Mutual Insurance Company',
  'West Bend',
  'Western National',
  'Western Reserve Group',
  'Westfield',
  'White Mountains',
  'Wilshire',
  'Wilson Mutual',
  'Wind Haven',
  'Windsor',
  'Wisconsin Mutual',
  'Wolverine Mutual Insurance Company',
  'Workmens Auto Insurance Company',
  'Worth Casualty Insurance Company',
  'Zurich',
  'Other Standard',
  'Other Non-Standard',
  'No Prior Insurance',
];
export const primaryUseOptions = [
  'To/From Work',
  'To/From School',
  'Business',
  'Pleasure',
  'Farming',
];
export const states = [
  'Alabama',
  'Alaska',
  'American Samoa',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District of Columbia',
  'Federated States of Micronesia',
  'Florida',
  'Georgia',
  'Guam',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Marshall Islands',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Northern Mariana Islands',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Palau',
  'Pennsylvania',
  'Puerto Rico',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virgin Island',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

export const IndustryEnums = [
  { text: 'Agricultural / Forestry / Fish', value: 'Agriclt/Forestry/Fish' },
  { text: 'Art / Design / Media ', value: 'Art/Design/Media' },
  { text: 'Banking / Finance/ Real Estate', value: 'Banking/Finance/RE' },
  { text: 'Business / Sales / Office', value: 'Business/Sales/Offi' },
  { text: 'Construction / Energy / Tradesperson', value: 'Construct/EnrgyTrds' },
  { text: 'Disabled', value: 'Disabled' },
  { text: 'Education / Library', value: 'Education/Library' },
  { text: 'Engineering / Architecture / Science / Math', value: 'Engr/Archt/Sci/Math' },
  { text: 'Government / Military', value: 'Government/Military' },
  { text: 'Homemaker / Houseperson', value: 'Homemaker/Houseprsn' },
  { text: 'Information Technology', value: 'Info Tech' },
  { text: 'Insurance', value: 'Insurance' },
  { text: 'Legal / Law Enforcement / Security', value: 'Lgl/Law Enfcmt/Sec' },
  { text: 'Maintenence / Repair / Housekeeping', value: 'Maint/Rpr/Hsekeep' },
  { text: 'Manufacturing / Production', value: 'Mfg/Production' },
  { text: 'Medical / Social Services / Religion', value: 'Med/Soc Svcs/Relig' },
  { text: 'Other', value: 'Other' },
  { text: 'Personal Care / Service', value: 'Person.Care/Service' },
  { text: 'Restaurants / Hotel Services', value: 'Rest/Hotel Services' },
  { text: 'Retired', value: 'Retired' },
  { text: 'Sports / Recreation', value: 'Sports/Recreation' },
  { text: 'Student', value: 'Student' },
  { text: 'Travel / Transport / Warehouse', value: 'Trvl/Trnsprt/Warehs' },
  { text: 'Unemployed', value: 'Unemployed' },
];
export const Ocuppations = {
  'Agriclt/Forestry/Fish': [
    { text: 'Agricultural Inspection / Grader', value: 'Agr Inspect/Grader' },
    { text: 'Arborist', value: 'Arborist' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Equipment Operator', value: 'Equip. Operator' },
    { text: 'Farm / Ranch Owner', value: 'Farm/Ranch Owner' },
    { text: 'Farm / Ranch Worker', value: 'Farm/Ranch Worker' },
    { text: 'Fisherman', value: 'Fisherman' },
    { text: 'Florist', value: 'Florist' },
    { text: 'Laborer / Worker', value: 'Laborer/Worker' },
    { text: 'Landscape / Nursery Worker', value: 'Landscape/NursryWkr' },
    { text: 'Landscaper', value: 'Landscaper' },
    { text: 'Logger', value: 'Logger' },
    { text: 'Millworker', value: 'Millworker' },
    { text: 'Other', value: 'Other' },
    { text: 'Ranger', value: 'Ranger' },
    { text: 'Supervisor', value: 'Supervisor' },
    { text: 'Timber Grader / Scaler', value: 'Timber Grader/Scale' },
    { text: 'Undergraduate', value: 'Undergraduate' },
  ],
  'Art/Design/Media': [
    { text: 'Actor', value: 'Actor' },
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Announcer / Broadcaster', value: 'Announcer/Broadcstr' },
    { text: 'Artist / Animator', value: 'Artist/Animator' },
    { text: 'Author / Writer', value: 'Author/Writer' },
    { text: 'Choreography / Dancer', value: 'Choreography/Dancer' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Composer / Director', value: 'Composer/Director' },
    { text: 'Curator', value: 'Curator' },
    { text: 'Designer', value: 'Designer' },
    { text: 'Editor', value: 'Editor' },
    { text: 'Journalist / Reporter', value: 'Journalist/Reporter' },
    { text: 'Musician / Singer', value: 'Musician/Singer' },
    { text: 'Other', value: 'Other' },
    { text: 'Printer', value: 'Printer' },
    { text: 'Producer', value: 'Producer' },
    { text: 'Production Crew', value: 'Production Crew' },
    { text: 'Projectionist', value: 'Projectionist' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Ticket Sales / Usher', value: 'Ticket Sales/Usher' },
  ],
  'Banking/Finance/RE': [
    { text: 'Accountant / Auditor', value: 'Accountant/Auditor' },
    { text: 'Admin Assist', value: 'Admin Assist' },
    { text: 'Analyst / Broker', value: 'Analyst/Broker' },
    { text: 'Bookkeeper', value: 'Bookkeeper' },
    { text: 'Branch Manager', value: 'Branch Manager' },
    { text: 'CSR / Teller', value: 'CSR/Teller' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Collections', value: 'Collections' },
    { text: 'Consultant', value: 'Consultant' },
    { text: 'Controller', value: 'Controller' },
    { text: 'Credit / Loan Management', value: 'Mgr-Credit/Loan' },
    { text: 'Director / Administrator', value: 'Director/Administr' },
    { text: 'Executive', value: 'Executive' },
    { text: 'Financial Advisor', value: 'Financial Advisor' },
    { text: 'Financial Instruments Trader', value: 'Trader,Finan Instru' },
    { text: 'Investment Banker', value: 'Investment Banker' },
    { text: 'Investor', value: 'Investor' },
    { text: 'Loan / Escrow Processor', value: 'Loan/EscrowProcess' },
    { text: 'Other', value: 'Other' },
    { text: 'Portfolio / Production Manager', value: 'Mgr-Portfolio/Prod.' },
    { text: 'Property Management', value: 'Mgr-Property' },
    { text: 'Realtor', value: 'Realtor' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Sales Agent / Representative', value: 'SalesAgt/Represent.' },
    { text: 'Underwriter', value: 'Underwriter' },
  ],
  'Business/Sales/Offi': [
    { text: 'Account Executive', value: 'Account Executive' },
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Buyer', value: 'Buyer' },
    { text: 'Consultant', value: 'Consultant' },
    { text: 'Customer Service Representative', value: 'CSR' },
    { text: 'Department / Store Manager', value: 'Mgr-Dept/Store' },
    { text: 'Director / Administrator', value: 'Director/Administr' },
    { text: 'District Management', value: 'Mgr - District' },
    { text: 'Executive', value: 'Executive' },
    { text: 'Finance Management', value: 'Mgr - Finance' },
    { text: 'General Operations Manager', value: 'Mgr-General Opers' },
    { text: 'H.R. / Public Relations Manager', value: 'Mgr-H.R./PublicRel' },
    { text: 'H.R. Representative', value: 'H.R. Representative' },
    { text: 'Marketing / Sales Management', value: 'Mgr-Mkt/Sales' },
    { text: 'Marketing Researcher', value: 'Marketing Researchr' },
    { text: 'Messenger / Courier', value: 'Messenger/Courier' },
    { text: 'Office Clerk', value: 'Clerk-Office' },
    { text: 'Office Manager / Supervisor', value: 'Mgr/Supervisr-Offic' },
    { text: 'Other', value: 'Other' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Sales - Counter / Rental ', value: 'Sales-Counter/Rentl' },
    { text: 'Sales - Home Based', value: 'Sales-Home Based' },
    { text: 'Sales - Manufacturer Rep', value: 'Sales-Mfg Rep' },
    { text: 'Sales - Retail / Wholesale', value: 'Sales-Retail/Whlsle' },
    { text: 'Sales - Route / Vendor', value: 'Sales-Route/Vendor' },
  ],
  'Construct/EnrgyTrds': [
    { text: 'Boiler Operator / Maker', value: 'Boiler Oper/Maker' },
    { text: 'Bricklayer / Mason', value: 'Bricklayer/Mason' },
    { text: 'Carpenter', value: 'Carpenter' },
    { text: 'Carpet Installer', value: 'Carpet Installer' },
    { text: 'Concrete Worker', value: 'Concrete Worker' },
    { text: 'Conststruction Project Mangement', value: 'Constrct Proj Mgr' },
    { text: 'Contractor', value: 'Contractor' },
    { text: 'Crane Operator', value: 'Crane Operator' },
    { text: 'Electrician / Linesmn', value: 'Electrician/Linesmn' },
    { text: 'Elevator Tech / Installation', value: 'ElevatorTech/Instl' },
    { text: 'Equipment Operator', value: 'Equip. Operator' },
    { text: 'Floor Layer / Finisher', value: 'FloorLayer/Finisher' },
    { text: 'Foreman / Supervisor', value: 'Foreman/Supervisor' },
    { text: 'Handyman', value: 'Handyman' },
    { text: 'Heat / Air Technician', value: 'Heat/Air Technician' },
    { text: 'Inspector', value: 'Inspector' },
    { text: 'Laborer / Worker', value: 'Laborer/Worker' },
    { text: 'Metalworker', value: 'Metalworker' },
    { text: 'Miner', value: 'Miner' },
    { text: 'Oil / Gas Drilling / Rig Operation', value: 'Oil/GasDril/RigOpr' },
    { text: 'Other', value: 'Other' },
    { text: 'Painter', value: 'Painter' },
    { text: 'Plaster / Drywall / Stucco', value: 'Plstr/Drywall/Stuc' },
    { text: 'Plumber', value: 'Plumber' },
    { text: 'Roofer', value: 'Roofer' },
  ],
  Disabled: [{ text: 'Disabled', value: 'Disabled' }],
  'Education/Library': [
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Audio / Visual Technician', value: 'Audio-Visual Tech.' },
    { text: 'Child / Daycare Worker', value: 'Child/DayCare Wrker' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Counselor', value: 'Counselor' },
    { text: 'Graduate Teacher / Assistant', value: 'Grad. Teaching/Asst' },
    { text: 'Instructor - Vocational', value: 'Instructor-Vocation' },
    { text: 'Librarian / Curator', value: 'Librarian/Curator' },
    { text: 'Other', value: 'Other' },
    { text: 'Professor, College', value: 'Professor, College' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Superintendent', value: 'Superintendent' },
    { text: 'Teacher, College', value: 'Teacher, College' },
    { text: 'Teacher, K-12', value: 'Teacher, K-12' },
    { text: 'Teaching Assistant / Aide', value: 'Teaching Asst/Aide' },
    { text: 'Tutor', value: 'Tutor' },
  ],
  'Engr/Archt/Sci/Math': [
    { text: 'Actuary', value: 'Actuary' },
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Analyst', value: 'Analyst' },
    { text: 'Architect', value: 'Architect' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Clinical Data Coordinator', value: 'Clinical Data Coord.' },
    { text: 'Drafter', value: 'Drafter' },
    { text: 'Engineer', value: 'Engineer' },
    { text: 'Manager - Project', value: 'Manager-Project' },
    { text: 'Manager - R&D', value: 'Manager-R&D' },
    { text: 'Mathematician', value: 'Mathematician' },
    { text: 'Other', value: 'Other' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Research Program Director', value: 'Research Prog. Dir.' },
    { text: 'Researcher', value: 'Researcher' },
    { text: 'Scientist', value: 'Scientist' },
    { text: 'Sociologist', value: 'Sociologist' },
    { text: 'Surveyor / Mapmaker', value: 'Surveyor/Mapmaker' },
    { text: 'Technician', value: 'Technician' },
  ],
  'Government/Military': [
    { text: 'Accountant / Auditor', value: 'Accountant/Auditor' },
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Analyst', value: 'Analyst' },
    { text: 'Attorney', value: 'Attorney' },
    { text: 'Chief Executive', value: 'Chief Executive' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Commissioner', value: 'Commissioner' },
    { text: 'Council member', value: 'Council member' },
    { text: 'Director / Administrator', value: 'Director/Administr' },
    { text: 'Enlisted Military Personnel (E 1-4)', value: 'Enlst Mil Prsnl E1-4' },
    { text: 'Legislator', value: 'Legislator' },
    { text: 'Mayor / City Manager', value: 'Mayor/City Manager' },
    { text: 'Meter Reader', value: 'Meter Reader' },
    { text: 'Non-Commissioned Officer (E 5-9)', value: 'NCO (E5-9)' },
    { text: 'Officer - Commissiond', value: 'Officer-Commissiond' },
    { text: 'Officer - Warrant', value: 'Officer-Warrant' },
    { text: 'Other', value: 'Other' },
    { text: 'Park Ranger', value: 'Park Ranger' },
    { text: 'Planner', value: 'Planner' },
    { text: 'Postmaster', value: 'Postmaster' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Regulator', value: 'Regulator' },
    { text: 'US Postal Worker', value: 'US Postal Worker' },
  ],
  'Homemaker/Houseprsn': [
    { text: 'Homemaker / Houseperson', value: 'Homemaker/Houseprsn' },
  ],
  'Info Tech': [
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Analyst', value: 'Analyst' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Director / Administrator', value: 'Director/Administr' },
    { text: 'Engineer - Hardware', value: 'Engineer-Hardware' },
    { text: 'Engineer - Software', value: 'Engineer-Software' },
    { text: 'Engineer - Systems', value: 'Engineer-Systems' },
    { text: 'Executive', value: 'Executive' },
    { text: 'Manager - Systems', value: 'Manager-Systems' },
    { text: 'Network Administrator', value: 'Network Admin' },
    { text: 'Other', value: 'Other' },
    { text: 'Programmer', value: 'Programmer' },
    { text: 'Project Coordinator', value: 'Project Coordinator' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Support Technician', value: 'Support Technician' },
    { text: 'Systems Security', value: 'Systems Security' },
    { text: 'Technical Writer', value: 'Technical Writer' },
    { text: 'Web Developer', value: 'Web Developer' },
  ],
  Insurance: [
    { text: 'Accountant / Auditor', value: 'Accountant/Auditor' },
    { text: 'Actuarial Clerk', value: 'Actuarial Clerk' },
    { text: 'Actuary', value: 'Actuary' },
    { text: 'Admin Assist', value: 'Admin Assist' },
    { text: 'Agent / Broker', value: 'Agent/Broker' },
    { text: 'Analyst', value: 'Analyst' },
    { text: 'Attorney', value: 'Attorney' },
    { text: 'Claims Adjuster', value: 'Claims Adjuster' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Commissioner', value: 'Commissioner' },
    { text: 'Customer Service Representative', value: 'CSR' },
    { text: 'Director / Administrator', value: 'Director/Administr' },
    { text: 'Executive', value: 'Executive' },
    { text: 'Other', value: 'Other' },
    { text: 'Product Manager', value: 'Product Manager' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Sales Representative', value: 'Sales Rep' },
  ],
  'Lgl/Law Enfcmt/Sec': [
    { text: 'Airport Security Officer', value: 'Airport Sec Ofcr' },
    { text: 'Animal Control Officer', value: 'Animal Control Ofcr' },
    { text: 'Attorney', value: 'Attorney' },
    { text: 'Bailiff', value: 'Bailiff' },
    { text: 'Corrections Officer', value: 'Corrections Officer' },
    { text: 'Court Clerk / Reporter', value: 'Court Clrk/Reporter' },
    { text: 'Deputy Sheriff', value: 'Deputy Sheriff' },
    { text: 'Dispatcher', value: 'Dispatcher' },
    { text: 'Examiner', value: 'Examiner' },
    { text: 'Federal Agent / Marshal', value: 'Fed Agt/Marshall' },
    { text: 'Fire Chief', value: 'Fire Chief' },
    { text: 'Fire Fighter / Supervisor ', value: 'Fire Fighter/Supv.' },
    { text: 'Game Officer / Investigator', value: 'Gaming Ofcr/Invest' },
    { text: 'Highway Patrol Officer', value: 'Highway Patrol Ofcr' },
    { text: 'Judge / Hearing Officer', value: 'Judge/Hearing Ofcr' },
    { text: 'Legal Assistant / Secretary', value: 'Legal Asst./Sec' },
    { text: 'Other', value: 'Other' },
    { text: 'Paralegal / Law Clerk', value: 'Paralegal/Law Clerk' },
    { text: 'Police Chief', value: 'Police Chief' },
    { text: 'Police Detective / Investigator', value: 'Police Det/Investgr' },
    { text: 'Police Officer / Supervisor', value: 'Police Offcr/Supvr' },
    { text: 'Private Investigator / Detective', value: 'Prvt Invest/Detec.' },
    { text: 'Process Server', value: 'Process Server' },
    { text: 'Security Guard', value: 'Security Guard' },
    { text: 'Sheriff', value: 'Sheriff' },
    { text: 'Underwriter', value: 'Underwriter' },
  ],
  'Maint/Rpr/Hsekeep': [
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Building Maintenance Engineer', value: 'Bldg Maint Engineer' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Custodian / Janitor', value: 'Custodian/Janitor' },
    { text: 'Electrician', value: 'Electrician' },
    { text: 'Factory Worker', value: 'Factory Worker' },
    { text: 'Field Service Technician', value: 'Field Service Tech.' },
    { text: 'Foreman / Supervisor', value: 'Foreman/Supervisor' },
    { text: 'Furniture Finisher', value: 'Furniture Finisher' },
    { text: 'Handyman', value: 'Handyman' },
    { text: 'Heat / Air Conditioner Repair', value: 'Heat/AirCond Repair' },
    { text: 'Housekeeper / Maid', value: 'Housekeeper/Maid' },
    { text: 'Inspector', value: 'Inspector' },
    { text: 'Jeweler', value: 'Jeweler' },
    { text: 'Landscape / Grounds Maintenance', value: 'Lndscpe/Grnds Maint' },
    { text: 'Machine Operator', value: 'Machine Operator' },
    { text: 'Maintenance Mechanic', value: 'Maint Mechanic' },
    { text: 'Mechanic', value: 'Mechanic' },
    { text: 'Other', value: 'Other' },
    { text: 'Other', value: 'Other' },
  ],
  'Med/Soc Svcs/Relig': [
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Clergy', value: 'Clergy' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Client Care Worker', value: 'Client Care Worker' },
    { text: 'Dental Hygenist', value: 'Dental Hygenist' },
    { text: 'Dentist', value: 'Dentist' },
    { text: 'Doctor', value: 'Doctor' },
    { text: 'Hospice Volunteer', value: 'Hospice Volunteer' },
    { text: 'Medical Assistant / Dentist / Vet', value: 'Assist-Med/Dent/Vet' },
    { text: 'Mortician', value: 'Mortician' },
    { text: 'Nurse - C.N.A.', value: 'Nurse - C.N.A.' },
    { text: 'Nurse - LPN', value: 'Nurse - LPN' },
    { text: 'Nurse - RN', value: 'Nurse - RN' },
    { text: 'Nurse Practitioner', value: 'Nurse Practitioner' },
    { text: 'Optometrist', value: 'Optometrist' },
    { text: 'Other', value: 'Other' },
    { text: 'Paramedic / EM Tech', value: 'Paramedic/EM Tech' },
    { text: 'Pharmacist', value: 'Pharmacist' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Social Worker', value: 'Social Worker' },
    { text: 'Support Services', value: 'Support Services' },
    { text: 'Technician', value: 'Technician' },
    { text: 'Therapist', value: 'Therapist' },
    { text: 'Veterinarian', value: 'Veterinarian' },
  ],
  'Mfg/Production': [
    { text: 'Packer', value: 'Packer' },
    { text: 'Plant Manager', value: 'Plant Manager' },
    { text: 'Printer / Bookbinder', value: 'Printer/Bookbinder' },
    { text: 'Quality Control', value: 'Quality Control' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Refining Operator', value: 'Refining Operator' },
    { text: 'Shoemaker', value: 'Shoemaker' },
    { text: 'Tailor / Custom Sewer', value: 'Tailor/Custom Sewer' },
    { text: 'Textile Worker', value: 'Textile Worker' },
    { text: 'Upholsterer', value: 'Upholsterer' },
  ],
  Other: [{ text: 'Other', value: 'Other' }],
  'Person.Care/Service': [
    { text: 'Caregiver', value: 'Caregiver' },
    { text: 'Dry Cleaner / Laundry', value: 'Dry Cleaner/Laundry' },
    { text: 'Hair Stylist / Barber', value: 'Hair Stylist/Barber' },
    { text: 'Housekeeper', value: 'Housekeeper' },
    { text: 'Manicurist', value: 'Manicurist' },
    { text: 'Masseuse', value: 'Masseuse' },
    { text: 'Nanny', value: 'Nanny' },
    { text: 'Other', value: 'Other' },
    { text: 'Pet Services', value: 'Pet Services' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
  ],
  'Rest/Hotel Services': [
    { text: 'Baker', value: 'Baker' },
    { text: 'Bartender', value: 'Bartender' },
    { text: 'Bellhop', value: 'Bellhop' },
    { text: 'Bus Person', value: 'Bus Person' },
    { text: 'Caterer', value: 'Caterer' },
    { text: 'Chef', value: 'Chef' },
    { text: 'Concessionaire', value: 'Concessionaire' },
    { text: 'Concierge', value: 'Concierge' },
    { text: 'Cook / Worker -Fast Food', value: 'Cook/Wrkr-Fast Food' },
    { text: 'Cook- Restaurant / Cafeteria', value: 'Cook-Rest/Cafeteria' },
    { text: 'Delivery Person', value: 'Delivery Person' },
    { text: 'Desk Clerk', value: 'Desk Clerk' },
    { text: 'Dishwasher', value: 'Dishwasher' },
    { text: 'Food Production / Packing', value: 'Food Prod/Packing' },
    { text: 'Host / Maitre d', value: 'Host/Maitre d' },
    { text: 'Housekeeper / Maid', value: 'Housekeeper/Maid' },
    { text: 'Manager', value: 'Manager' },
    { text: 'Other', value: 'Other' },
    { text: 'Valet', value: 'Valet' },
    { text: 'Waiter / Waitress', value: 'Waiter/Waitress' },
    { text: 'Wine Steward', value: 'Wine Steward' },
  ],
  Retired: [{ text: 'Retired', value: 'Retired' }],
  'Sports/Recreation': [
    { text: 'Activity / Recreation Assistant', value: 'Activity/Recre.Asst' },
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Agent', value: 'Agent' },
    { text: 'Athlete', value: 'Athlete' },
    { text: 'Camp Counselor / Leader', value: 'CampCounselor/Lead' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Coach', value: 'Coach' },
    { text: 'Concessionaire', value: 'Concessionaire' },
    { text: 'Director, Program', value: 'Director, Program' },
    { text: 'Event Manager / Promoter', value: 'Event Mgr/Promoter' },
    { text: 'Fitness Club Management', value: 'Mgr - Fitness Club' },
    { text: 'Life Guard', value: 'Life Guard' },
    { text: 'Other', value: 'Other' },
    { text: 'Park Ranger', value: 'Park Ranger' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Sales Ticket / Membership', value: 'Sales-Tkt/Mmbrshp' },
    { text: 'Sports Broadcasting / Journalism', value: 'SportsBrdcstr/Journ' },
    { text: 'Trainer / Instructor', value: 'Trainer/Instructor' },
    { text: 'Umpire / Referee', value: 'Umpire/Referee' },
  ],
  Student: [
    { text: 'Graduate Student', value: 'Graduate Student' },
    { text: 'High school', value: 'High school' },
    { text: 'Other', value: 'Other' },
    { text: 'Undergraduate', value: 'Undergraduate' },
  ],
  'Trvl/Trnsprt/Warehs': [
    { text: 'Administrative Assistant', value: 'Admin Assist' },
    { text: 'Air Traffic Control', value: 'Air Traffic Control' },
    { text: 'Airport Ops Crew', value: 'Airport Ops Crew' },
    { text: 'Bellhop / Porter', value: 'Bellhop/Porter' },
    { text: 'Clerk', value: 'Clerk' },
    { text: 'Crane Loader / Operator', value: 'Crane Loader/Oper' },
    { text: 'Dispatcher', value: 'Dispatcher' },
    { text: 'Driver - Bus / Streetcar', value: 'Driver-Bus/Strcar' },
    { text: 'Driver - Taxi / Limo', value: 'Driver-Taxi/Limo' },
    { text: 'Driver- Truck / Delivery ', value: 'Driver-Truck/Delvry' },
    { text: 'Flight Attendant', value: 'Flight Attendant' },
    { text: 'Forklift Operator', value: 'Forklift Operator' },
    { text: 'Laborer', value: 'Laborer' },
    { text: 'Longshoreman', value: 'Longshoreman' },
    { text: 'Mate / Sailor', value: 'Mate/Sailor' },
    { text: 'Other', value: 'Other' },
    { text: 'Parking Lot Attendant', value: 'Parking Lot Attend' },
    { text: 'Pilot / Captain / Engineer', value: 'Pilot/Capt/Eng' },
    { text: 'Railroad Worker', value: 'Railroad Worker' },
    { text: 'Receptionist / Secretary', value: 'Receptionist/Sec' },
    { text: 'Shipping / Receiving Clerk', value: 'Shipping/RecClk' },
    { text: 'Subway / Light Rail Operator', value: 'Subway/LgtRail Oper' },
    { text: 'Ticket Agent', value: 'Ticket Agent' },
    { text: 'Transportation Specialist', value: 'Transportation Spec' },
    { text: 'Warehouse / Distribution Manager', value: 'Mgr Warehse/Dist' },
  ],
  Unemployed: [{ text: 'Unemployed', value: 'Unemployed' }],
};
