import {
  faCars,
  faMotorcycle,
  faRv,
  faHouseUser,
  faWindowFrame,
  faHouseFlood,
  faHomeLg,
  faCaravan,
  faBuilding,
  faEllipsisH,
  faHandHoldingMedical,
  faHeartbeat,
  faPlane,
  faDog,
  faStarOfLife,
  faTooth,
  faEye,
  faIdCardAlt,
} from '@fortawesome/pro-light-svg-icons';

export const vehicleInsurances = [
  { icon: faCars, text: 'Personal Auto', id: 1 },
  { icon: faMotorcycle, text: 'Motorcycle', id: 3 },
  { icon: faRv, text: 'Other' },
];
export const propertyInsurances = [
  { icon: faHouseUser, text: 'Condo' },
  { icon: faWindowFrame, text: 'Rental' },
  { icon: faHouseFlood, text: 'Flood' },
  { icon: faHomeLg, text: 'Homeowners' },
  { icon: faCaravan, text: 'Mobile Home' },
  { icon: faBuilding, text: 'Landlord' },
  { icon: faEllipsisH, text: 'Other' },
];
export const personalInsurances = [
  { icon: faHandHoldingMedical, text: 'Health' },
  { icon: faHeartbeat, text: 'Life(Whole)' },
  { icon: faHeartbeat, text: 'Life(Term)' },
  { icon: faPlane, text: 'Travel' },
  { icon: faDog, text: 'Pet' },
  { icon: faStarOfLife, text: 'Supplemental' },
  { icon: faTooth, text: 'Dental' },
  { icon: faEye, text: 'Vision' },
  { icon: faIdCardAlt, text: 'ID Theft' },
];
export const years = [
  { year: 2021 },
  { year: 2020 },
  { year: 2019 },
  { year: 2018 },
  { year: 2017 },
  { year: 2016 },
  { year: 2015 },
  { year: 2014 },
  { year: 2013 },
  { year: 2012 },
  { year: 2011 },
  { year: 2010 },
  { year: 2009 },
  { year: 2008 },
  { year: 2007 },
  { year: 2006 },
  { year: 2005 },
  { year: 2004 },
  { year: 2003 },
  { year: 2002 },
  { year: 2001 },
  { year: 2000 },
  { year: 1999 },
  { year: 1998 },
  { year: 1997 },
  { year: 1996 },
  { year: 1995 },
  { year: 1994 },
  { year: 1993 },
  { year: 1992 },
  { year: 1991 },
  { year: 1990 },
];

export const propertyDeductibleOptions = [
  'No Deductible',
  '$250',
  '$500',
  '$750',
  '$1000',
  '$1500',
  '$2000',
  '$2500',
  '$5000',
  '1%',
  '2%',
  '3%',
  '4%',
  '5%',
  '6%',
  '7%',
  '8%',
  '9%',
  '10%',
];
